version: "3.5"
services:
  wishlist_api:
    image: "wishlist_api"
    ports:
     - 2512:2512
    environment:
     - WISHLIST_API_PORTNUM=2512
     - WISHLIST_DB_USERNAME=wishlist_user
     - WISHLIST_DB_PASSWORD=jqXg-JCq%zWGFGsj9w&aBjQaE#f7cgCm
     - WISHLIST_DB_DATABASE=wishlist
     - WISHLIST_DB_HOSTNAME=wishlist_db
     - WISHLIST_API_DOMAIN=www.pearcenet.ch
     - WISHLIST_TOK_SIGNING_KEY=thisisatest
  wishlist_db:
    image: "mysql"
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=wishlist_user
      - MYSQL_PASSWORD=jqXg-JCq%zWGFGsj9w&aBjQaE#f7cgCm
      - MYSQL_ROOT_PASSWORD=jqXg-JCq%zWGFGsj9w&aBjQaE#f7cgCm
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - /var/wishlist_api/mysql:/var/lib/mysql