version: "3.5"
services:
  wishlist_api:
    image: "wishlist_api"
    ports:
     - 2512:2512
    env_file:
      - .env
    environment:
     - WISHLIST_API_PORTNUM=2512
     - WISHLIST_DB_USERNAME=wishlist_user
     - WISHLIST_DB_DATABASE=wishlist
     - WISHLIST_DB_HOSTNAME=wishlist_db
     - WISHLIST_API_DOMAIN=www.pearcenet.ch
    volumes:
     - /etc/letsencrypt:/certs:ro
  wishlist_db:
    image: "mysql"
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      - MYSQL_USERNAME=wishlist_user
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - /var/wishlist_api/mysql:/var/lib/mysql